
import {
  LayoutDashboard,
  Users,
  CheckSquare,
  Megaphone,
  CalendarDays,
  BookUser,
  MessagesSquare,
  Calendar,
  CreditCard,
  Clapperboard,
  ClipboardList,
  FileText,
  BookCopy,
  BookText,
  GraduationCap,
  DoorOpen,
  Settings,
  Palette,
  DollarSign,
  HelpCircle,
  BookOpen,
  Receipt,
  TrendingUp,
  Landmark,
  CalendarCheck,
  Star,
  ShieldCheck,
  School,
} from 'lucide-react';

export const navLinks = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/students", label: "Student Profiles", icon: Users },
  { href: "/teachers", label: "Teacher Directory", icon: BookUser },
  { href: "/classes", label: "Classes", icon: GraduationCap },
  { href: "/subjects", label: "Subjects", icon: BookText },
  { href: "/rooms", label: "Rooms", icon: DoorOpen },
  { href: "/assignments", label: "Subject Assignments", icon: BookCopy },
  { href: "/timetables", label: "Timetables", icon: CalendarDays },
  { href: "/attendance", label: "Attendance", icon: CheckSquare },
  { href: "/homework", label: "Homework", icon: ClipboardList },
  { href: "/lesson-plans", label: "Lesson Plans", icon: BookOpen },
  { href: "/exams", label: "Quizzes & Exams", icon: FileText },
  { href: "/announcements", label: "Announcements", icon: Megaphone },
  { href: "/calendar", label: "Events Calendar", icon: Calendar },
  { href: "/communication", label: "Communication", icon: MessagesSquare },
  { href: "/fees", label: "Fee Collection", icon: CreditCard },
  { href: "/finance", label: "Finance", icon: Landmark },
  { href: "/leave-management", label: "Leave Management", icon: CalendarCheck },
  { href: "/billing", label: "Billing", icon: CreditCard },
  { href: "/income", label: "Income", icon: TrendingUp, isHidden: true },
  { href: "/expenses", label: "Financial Overview", icon: Receipt, isHidden: true },
  { href: "/payroll", label: "Payroll", icon: DollarSign, isHidden: true },
  { href: "/ai-setup-guide", label: "AI Setup Guide", icon: HelpCircle, isHidden: true },
  { href: "/timetables/configure", label: "Time Slots", icon: Settings, isSettings: true, isHidden: true },
  { href: "/settings", label: "Theme Settings", icon: Palette, isSettings: true },
  { href: "/subscription", label: "Subscription", icon: Star, isSettings: true },
  { href: "/super-admin", label: "Schools", icon: School, isHidden: true },
  { href: "/super-admin/billing", label: "Platform Billing", icon: ShieldCheck, isHidden: true },
  // This is a new link that should be hidden from the sidebar
  { href: "/classes/[id]/report-card/[studentId]", label: "Report Card", icon: FileText, isHidden: true },
  { href: "/classes/[id]", label: "View Class", icon: GraduationCap, isHidden: true },
  { href: "/classes/[id]/results/[studentId]", label: "Report Book Editor", icon: FileText, isHidden: true },
  { href: "/exams/[examId]/edit", label: "Edit Exam", icon: FileText, isHidden: true },
  { href: "/exams/[examId]/take", label: "Take Exam", icon: FileText, isHidden: true },
  { href: "/exams/[examId]/results", label: "Exam Results", icon: FileText, isHidden: true },
];
